services:
  - type: web
    name: iam-tfba
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/Kirsnickk/Snipe
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /login
    disk:
      name: snipe-data
      mountPath: /var/lib/snipeit
      sizeGB: 5
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://iam-tfba.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: APP_LOCALE
        value: en
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/lib/snipeit/snipeit.sqlite
      - key: FILESYSTEM_DISK
        value: local
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: PHP_UPLOAD_LIMIT
        value: "25"
      - key: SEED_ADMIN_EMAIL
        value: admin@kirsnickk.com
      - key: SEED_ADMIN_PASSWORD
        generateValue: true
